### ISSUE TITLE
can not run docker-compose up

### ISSUE THREAD

**Issue by naiwungmusic** [SpiralOutDotEu/dockervel#2]
It error

`In file '.\docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.`

With

> Docker version 1.9.1, build a34a1d5
> docker-compose version 1.5.2, build e5cf49d

**Comment by nikoumba** [comment]
You need version Docker 1.10, docker-machine and docker-compose 1.7 to run it.
check [here](http://www.spiralout.eu/2015/12/docker-installation-in-linux-mint-and.html) to install them,
or
`git checkout  tags/v0.1` to use the older version of dockervel
